# Generated by Django 4.0.6 on 2022-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nomdescricao_longa',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(default=' ', max_length=25000),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.TextField(default=' ', max_length=155),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.TextField(default=' ', max_length=155),
        ),
    ]
