# Generated by Django 4.0.6 on 2022-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_marca_alter_produto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modelo',
            field=models.CharField(max_length=155),
        ),
    ]
