# Generated by Django 4.0.6 on 2022-09-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_descricao_longa_alter_produto_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='descricao_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_longa',
            new_name='descricao_tecnica',
        ),
    ]
