# Generated by Django 4.0.6 on 2022-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_rename_descricao_curta_produto_descricao_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(max_length=1000),
        ),
    ]
