# Generated by Django 4.0.6 on 2022-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_produto_imagem_1_produto_imagem_2_produto_imagem_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
