# Generated by Django 4.0.6 on 2022-09-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_tecnica',
            field=models.TextField(max_length=25000, verbose_name='Ficha Técnica'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo'),
        ),
    ]
