# Generated by Django 4.0.6 on 2022-09-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produto_descricao_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qualidade_equipamento',
            field=models.CharField(choices=[('N', 'Novo'), ('S', 'Seminovo'), ('U', 'Usado')], default='N', max_length=1),
        ),
    ]
