# Generated by Django 4.0.6 on 2022-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_produto_qualidade_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qualidade_equipamento',
            field=models.CharField(choices=[('N', 'Novo'), ('S', 'Seminovo (até 4 meses de uso)'), ('U', 'Usado')], default='N', max_length=1, verbose_name='Qualidade do produto'),
        ),
    ]
