# Generated by Django 4.0.6 on 2022-11-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_produto_qualidade_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produto_imagens/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_1',
            field=models.ImageField(upload_to='produto_imagens/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_2',
            field=models.ImageField(upload_to='produto_imagens/%Y/%m/'),
        ),
    ]
