# Generated by Django 4.0.6 on 2022-11-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
