# Generated by Django 4.0.6 on 2022-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_data_criacao_pedido_data_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
